### ISSUE TITLE
"Spaced ellipses" are parsed as sentences

### ISSUE THREAD

**Issue by ma53** [seblindfors/Immersion#3]
While questing today, I noticed that some quest-writers at Blizzard employ ellipses with spaces between the periods.  The addon interprets these as individual sentences and they come through as segments to click through in-game.  Example quests:

http://www.wowhead.com/quest=26683/look-to-the-stars
http://www.wowhead.com/quest=26684/the-insane-ghoul

I've never worked with Lua scripting or WoW addons before (I'm primarily a Javascript developer), but I absolutely love this addon and so I thought I'd take a crack at it and maybe do something useful.  I've submitted a pull request that replaces these "spaced ellipses" with normal ones.

https://github.com/seblindfors/Immersion/pull/2

I've tested it on my game client and it seems to work as intended.  I'm not sure this is the way you would prefer to go about it, but there it is.  Thank you for your work on this Addon!  It's wonderful.

**Comment by seblindfors** [comment]
(response on your pull request)
